server:
     port: 8082
     servlet:
       context-path: /msurlslicer/api
      
spring:    
    datasource:
            platform: postgres  
            jdbc-url: jdbc:postgresql://libranzas-aplicaciones.chimul6agbmw.us-east-1.rds.amazonaws.com:5432/report_bank_instancia2
            username: report_bank
            password: 'the2aiDa3a@&EC2013'
            driver-class-name: org.postgresql.Driver
            hikari:
                maximum-pool-size: 20
                connection-timeout: 70000  
